[project]
name = "echec"
version = "1.0.1"
description = "Recognizing elliptic curves"
readme = "README.md"
authors = [
    { name = "Marc Penninga" }
]
requires-python = ">=3.9"
dependencies = [
    "gmpy2>=2.2.0",
    "sympy>=1.1",
]

[project.scripts]
echec = "echec.main:main"
